### ISSUE TITLE
PS4 UPDATE - Guilty Gear Xrd (Rev1+2)

### ISSUE THREAD

**Issue by chastetiddy** [InfraredAces/GP2040-CE-Compatibility-List#3]
| Game Title | GP2040-CE (PS3) | GP2040-CE (PS4) | GP2040-CE + Brook Wingman XE 2 Converter | Notes |
|------------|:---------------:|:---------------:|:----------------------------------------:|-------|
| Guilty Gear Xrd (Rev1+2)       |          |      ✅     |                                    |       |

**Comment by InfraredAces** [comment]
No longer maintaining GP2040-CE (PS4) compatibility column. Guilty Gear Xrd (Rev1+2) has been updated.
